### ISSUE TITLE
Optimization constraints

### ISSUE THREAD

**Issue by vigorPan** [baturaysaglam/RIS-MISO-Deep-Reinforcement-Learning#6]
Why the normalization of power can  satisfy the constraints of the optimization equation? If there are other constraints, what should we do？

**Comment by baturaysaglam** [comment]
because the constraint states that you should get a power value smaller than _or equal to_ the pre-specified power constraint value. normalizing the power will get you a value equal to the pre-specified constraint. hence, it satisfies the constraint. it is a bit sloppy but realizing this in the codebase is really hard. nonetheless, this version should work fine. 

I cannot directly answer the second question without knowing which components they regard.
